# This file was generated by GoReleaser. DO NOT EDIT.
cask "gt-telegram" do
  name "gt-telegram"
  desc "Telegram bridge for Gas Town overseer communication"
  homepage "https://github.com/leonletto/gt-telegram"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gt-telegram"

  on_macos do
    on_intel do
      url "https://github.com/leonletto/gt-telegram/releases/download/v#{version}/gt-telegram_#{version}_darwin_amd64.tar.gz"
      sha256 "5227820d0e1ac71bd55ec9d474f1e7015b39676d3d2838193125b4caab6a129b"
    end
    on_arm do
      url "https://github.com/leonletto/gt-telegram/releases/download/v#{version}/gt-telegram_#{version}_darwin_arm64.tar.gz"
      sha256 "e3bc9ca170efbd3700c8a25f16e7f2d349c24588527da001abadb4fb14b0617c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/leonletto/gt-telegram/releases/download/v#{version}/gt-telegram_#{version}_linux_amd64.tar.gz"
      sha256 "497a8cc5d0b79ebfbd48ab46b22f0269db87ced6c90d1e6420d86232caaec39e"
    end
    on_arm do
      url "https://github.com/leonletto/gt-telegram/releases/download/v#{version}/gt-telegram_#{version}_linux_arm64.tar.gz"
      sha256 "4959b6aa5ab52f9d5d43a173557debf652149e959318cd992bc4f4fbe5273ffb"
    end
  end

  # No zap stanza required
end
