# This file was generated by GoReleaser. DO NOT EDIT.
cask "gt-telegram" do
  name "gt-telegram"
  desc "Telegram bridge for Gas Town overseer communication"
  homepage "https://github.com/leonletto/gt-telegram"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gt-telegram"

  on_macos do
    on_intel do
      url "https://github.com/leonletto/gt-telegram/releases/download/v#{version}/gt-telegram_#{version}_darwin_amd64.tar.gz"
      sha256 "fd469afb731ffd01fbffb8d220487f573f147c4883268548bb461be502b95e54"
    end
    on_arm do
      url "https://github.com/leonletto/gt-telegram/releases/download/v#{version}/gt-telegram_#{version}_darwin_arm64.tar.gz"
      sha256 "2f22c6b6a1db36be48d861f60f552d80f9ac54eb2de9c148faa5767228479501"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/leonletto/gt-telegram/releases/download/v#{version}/gt-telegram_#{version}_linux_amd64.tar.gz"
      sha256 "630818ceb65cbf19744e023d46e06dff6d4ed12844d444215b2ea1eb841c6195"
    end
    on_arm do
      url "https://github.com/leonletto/gt-telegram/releases/download/v#{version}/gt-telegram_#{version}_linux_arm64.tar.gz"
      sha256 "1e1aab3d289a04036e89d79382e78fd1e170b993524fa17d24c3a9fcdc91d62f"
    end
  end

  # No zap stanza required
end
