# This file was generated by GoReleaser. DO NOT EDIT.
cask "thrum" do
  name "thrum"
  desc "Git-backed agent messaging and coordination CLI"
  homepage "https://github.com/leonletto/thrum"
  version "0.4.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "thrum"

  on_macos do
    on_intel do
      url "https://github.com/leonletto/thrum/releases/download/v#{version}/thrum_#{version}_darwin_amd64.tar.gz"
      sha256 "46863c0b8501edee8ae72e6e2928be0b246a05ed37b066fb159ce0a09f27d868"
    end
    on_arm do
      url "https://github.com/leonletto/thrum/releases/download/v#{version}/thrum_#{version}_darwin_arm64.tar.gz"
      sha256 "721c759b74a5a224c3ae8087191f0910bcaa4f221104c783a8d69bf2e4cc7085"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/leonletto/thrum/releases/download/v#{version}/thrum_#{version}_linux_amd64.tar.gz"
      sha256 "9b15038a0175ae750ed38f42e57c4924af885798fdcc97e5f7fe4326457efd0b"
    end
    on_arm do
      url "https://github.com/leonletto/thrum/releases/download/v#{version}/thrum_#{version}_linux_arm64.tar.gz"
      sha256 "13475e56524a67295d679b6bff30d04fab870a878f3073df79a2bf0f18b14d48"
    end
  end

  # No zap stanza required
end
