# This file was generated by GoReleaser. DO NOT EDIT.
cask "thrum" do
  name "thrum"
  desc "Git-backed agent messaging and coordination CLI"
  homepage "https://github.com/leonletto/thrum"
  version "0.5.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "thrum"

  on_macos do
    on_intel do
      url "https://github.com/leonletto/thrum/releases/download/v#{version}/thrum_#{version}_darwin_amd64.tar.gz"
      sha256 "bfa86a71bb5ce661ee78b3df624cfdb29c6108f5c942e514b55add5785e72fee"
    end
    on_arm do
      url "https://github.com/leonletto/thrum/releases/download/v#{version}/thrum_#{version}_darwin_arm64.tar.gz"
      sha256 "8d2e0b082994b2330f03f979047f698c98abe6ccaa59c2ecec50b6dc31cbea7a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/leonletto/thrum/releases/download/v#{version}/thrum_#{version}_linux_amd64.tar.gz"
      sha256 "357de57625989499ff3c08811cc18b73257d201b49aab6bd27a3c580c087dbbd"
    end
    on_arm do
      url "https://github.com/leonletto/thrum/releases/download/v#{version}/thrum_#{version}_linux_arm64.tar.gz"
      sha256 "c00dc08ef8182e2d786b86c21c5e7a259730e457adee2f72524095ee5dc310ad"
    end
  end

  # No zap stanza required
end
