# This file was generated by GoReleaser. DO NOT EDIT.
cask "thrum" do
  version "0.8.2"

  on_macos do
    on_intel do
      url "https://github.com/leonletto/thrum/releases/download/v#{version}/thrum_#{version}_darwin_amd64.tar.gz"
      sha256 "06f58eeb276fc6a26746eb8fb9113fbeb0f145e7a090208fe61a8f5019d83e5a"
    end
    on_arm do
      url "https://github.com/leonletto/thrum/releases/download/v#{version}/thrum_#{version}_darwin_arm64.tar.gz"
      sha256 "ee63c7a1f56baed20c2ab7423d7bb3500d55863040edef3f02c678dc678c2f7e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/leonletto/thrum/releases/download/v#{version}/thrum_#{version}_linux_amd64.tar.gz"
      sha256 "ae015df8127cb972fd5468c7937d2d3c7fa23645f38193dd1b7b52cf8aaf9a07"
    end
    on_arm do
      url "https://github.com/leonletto/thrum/releases/download/v#{version}/thrum_#{version}_linux_arm64.tar.gz"
      sha256 "473e2beb5acc19c5a17f3f5148e3faa22b915d6a0cc520c404c96065753dec64"
    end
  end

  name "thrum"
  desc "Git-backed agent messaging and coordination CLI"
  homepage "https://github.com/leonletto/thrum"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "thrum"

  # No zap stanza required

end
